### ISSUE TITLE
can't build dovi_meta on macOS

### ISSUE THREAD

**Issue by RaphFLC** [saindriches/dovi_meta#1]
Hello there,

I'm having some difficulties to build dovi_meta on macOS. 

error: failed to run custom build command for `dovi_meta v0.1.0 (/Users/rt/dovi_meta-master)`

Caused by:
  process didn't exit successfully: `/Users/rt/dovi_meta-master/debug/build/dovi_meta-017700cb314f61ba/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: could not find repository from '/Users/rt/dovi_meta-master'; class=Repository (6); code=NotFound (-3)', build.rs:10:20
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

Any ideas?

Thanks!

**Comment by RaphFLC** [comment]
I have tried this too:
# Cargo Build
SDKROOT=$(xcrun -sdk macosx --show-sdk-path) cargo build --target=x86_64-apple-darwin --release
SDKROOT=$(xcrun -sdk macosx --show-sdk-path) cargo build --target=aarch64-apple-darwin --release
But still not working.

error: failed to run custom build command for `dovi_meta v0.1.0 (/Users/rt/dovi_meta-master)`

Caused by:
  process didn't exit successfully: `/Users/rt/dovi_meta-master/target/release/build/dovi_meta-b9bfdb8dbe82877c/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: could not find repository from '/Users/rt/dovi_meta-master'; class=Repository (6); code=NotFound (-3)', build.rs:10:20
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by saindriches** [comment]
Hi, the build requires that a Git repository is present in the directory, so build with source code zip doesn’t work, I will fix that later. You can clone the repository with Git and it should work.

**Comment by RaphFLC** [comment]
Oh, alright!
Thank You!
