### ISSUE TITLE
Some values are not converted correctly

### ISSUE THREAD

**Issue by R3S3t9999** [saindriches/dovi_meta#4]
Hi, I think I found a bug in dovi_meta. It looks like some trim values have not been converted properly.

files: https://drive.google.com/drive/folders/1HnP5xF4lRPbOUbUiHPm1q1ba8dmJG7tF

for example, this is ''lift'' set to 0

dovi meta produce these values which are invalid metadata according to metafier and DEE:  <L8Trim>-1.0002443 -0.00048828125 0 0 0 0</L8Trim>

original resolve  correct values: <L8Trim>-1 0 0 0 0 0</L8Trim>

metafier error:
L1 Metadata Validation Test: PASS
L2 Metadata Validation Test: PASS
L3 Metadata Validation Test: PASS
L8 Metadata Validation Test: FAIL
L9 Metadata Validation Test: PASS
L11 Metadata Validation Test: PASS

09/16/2024/23:41:41.027000000 Metadata: ERROR list of ERRORS/WARNINGS:

ERROR: Level8 invalid value at shot: UniqueID = 5ba66581-abbe-4e6e-b215-24d4c531c013 @[0-71]

thank you!

**Comment by saindriches** [comment]
The new release should work.

**Comment by R3S3t9999** [comment]
Thanks but unfortunately it's still not working correctly and this new version now has changed my original ''power values''
https://slow.pics/c/Qd7NlF4k

files: https://drive.google.com/drive/u/0/folders/1HnP5xF4lRPbOUbUiHPm1q1ba8dmJG7tF
